name: Build, Publish and Deploy Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/wisecow:latest .

    - name: Log in to Docker Hub
      if: success()
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      if: success()
      run: docker push ${{ secrets.DOCKER_USERNAME }}/wisecow:latest

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2    

      - name: Set up Minikube
        if: success()
        run: |
             minikube start --cni=calico
             minikube addons enable ingress
             echo "Waiting for Minikube to be ready..."
             until kubectl get po -A | grep "kube-system" | grep "Running" > /dev/null; do
             sleep 10
             done

      - name: Create Deployment
        run: |
                kubectl apply -f deployment.yaml
                sleep 10
      
      - name: Create service
        run: |
               kubectl apply -f service.yaml
               sleep 10
      
      - name: Generate TLS certificates
        run: |
            openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=minikube.nip.io"
     
      - name: Create Kubernetes Secret
        run: |
            kubectl create secret tls tls-secret --cert=tls.crt --key=tls.key
            sleep 10
            
      - name: Create Ingress
        run: |
               export MINIKUBE_IP=$(minikube ip)
               awk -v host="$MINIKUBE_IP" '{gsub(/\$MINIKUBE_IP/, host); print}' ingress.yaml  > modified_ingress.yaml
               kubectl apply -f modified_ingress.yaml
               sleep 10

      - name: Output
        run: |
               export MINIKUBE_IP=$(minikube ip)
               echo "Running curl command:"
               curl -L -k "https://${MINIKUBE_IP}.nip.io"
               echo "Job Completed"
